# Generated by Django 5.2.4 on 2025-07-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
